apiVersion: v1
kind: Service
metadata:
  name: silverbullet-service
#  annotations:
#    metallb.universe.tf/loadBalancerIPs: 192.168.49.200
spec:
  type: LoadBalancer
  selector:
    app: silverbullet
  ports:
    - protocol: TCP
      port: 9376
      targetPort: 3000
